import DandyChair from '../icons/the-dandy-chair.jfif'
import RusticVase from '../icons/rustic-vase-set.jfif'
import SilkyVase from '../icons/the-silky-vase.jfif'
import LucyLamp from '../icons/the-lucy-lamp.jfif'
import LampSet from '../icons/lamp-set.png'
import VaseSet from '../icons/vase-set.png'
import WoodenChair from '../icons/wooden-chair.png'
import MetalChair from '../icons/metal-chair.png'
import WhiteTable from '../icons/white-table.avif'
import WoodenTable from '../icons/wooden-table.avif'
import DinnerTable from '../icons/dinner-table.png'
import TeaSet from '../icons/retro-tea-set.webp'
import DinnerPlate from '../icons/dinner-plate.webp'
import PinkSet from '../icons/pink-set.webp'
import SilverSet from '../icons/silver-set.webp'
import GoldenSet from '../icons/golden-set.webp'
import KitchenSet from '../icons/kitchen-set.webp'
import BlueTableware from '../icons/blue-tableware.webp'
import ChristmasSet from '../icons/christmas-dinner.jfif'
import Serveware from '../icons/serveware.jpg'
import ModernWallClock from '../icons/modern-wall-clock.jpg'
import ElegantArmchair from '../icons/elegant-armchair.webp'
import ModernCeramicBowl from '../icons/modern-ceramic-bowl.webp'
import ClassicDessertSpoonSet from '../icons/classic-dessert-spoon-set.webp'
import PorcelainSet from '../icons/porcelain-dinner-set.webp'
import StonewareServingPlatter from '../icons/stoneware-serving-platter.jpg'
import CoffeeTable from '../icons/coffee-table.webp'
import OakTable from '../icons/oak-table.jpg'
import LeatherChair from '../icons/leather-chair.webp'
import UpholsteredChair from '../icons/upholstered-chair.avif'
import MarbleTable from '../icons/marble-table.jpg'
import BlueCeramicVase from '../icons/blue-ceramic-vase.jpg'
import CrockerySet from '../icons/crockery-set.webp'
import RusticPlateSet from '../icons/rustic-plate-set.jpg'
import FloralTableware from '../icons/floral-tableware.webp'
import VintageTableware from '../icons/vintage-tableware.jpg'
import WoodenCutlery from '../icons/wooden-cutlery.webp'
import GoldPlatedCutlery from '../icons/gold-plated-cutlery.webp'

export default {
    collection: [
        {
            id: 1,
            img: DandyChair,
            type: 'chairs',
            title: 'The Dandy chair',
            price: '£250',
            count: 6,
            description: 'A timeless design, with premium materials features as one of our most popular and iconic pieces. The dandy chair is perfect for any stylish living space with beech legs and lambskin leather upholstery.',
            dimensions: { width: '110cm', height: '75cm', depth: '50cm' },
            inCart: false,
        },
        {
            id: 2,
            img: RusticVase,
            type: 'ceramics',
            title: 'Rustic Vase Set',
            price: '£155',
            count: 3,
            description: 'The Rustic Vase Set offers a touch of vintage charm to your decor. Each vase is crafted from high-quality ceramics with a distressed finish, perfect for displaying flowers or as a standalone piece.',
            dimensions: { height: '30cm', diameter: '15cm' },
            inCart: false,
        },
        {
            id: 3,
            img: SilkyVase,
            type: 'ceramics',
            title: 'The Silky Vase',
            price: '£125',
            count: 21,
            description: 'The Silky Vase is known for its smooth and glossy finish. This elegant piece is ideal for adding a sophisticated touch to your home, whether filled with fresh blooms or displayed empty.',
            dimensions: { height: '35cm', diameter: '20cm' },
            inCart: false,
        },
        {
            id: 4,
            img: LucyLamp,
            type: 'homeware',
            title: 'The Lucy Lamp',
            price: '£399',
            count: 5,
            description: 'The Lucy Lamp is a modern lighting solution with a sleek design. Its adjustable arm and bright LED light make it perfect for any desk or bedside table, offering both style and functionality.',
            dimensions: { height: '50cm', width: '20cm', depth: '20cm' },
            inCart: false,
        },
        {
            id: 5,
            img: SilverSet,
            type: 'cutlery',
            title: 'Silver Set',
            price: '£240',
            count: 2,
            description: 'The Silver Set includes all the essential cutlery for a sophisticated dining experience. Each piece is crafted from high-quality stainless steel with a polished finish that enhances any table setting.',
            dimensions: { length: '20cm' },
            inCart: false,
        },
        {
            id: 6,
            img: PinkSet,
            type: 'crockery',
            title: 'Pink Set',
            price: '£300',
            count: 14,
            description: 'The Pink Set adds a charming touch to your dining table. This collection of plates, bowls, and mugs is made from durable ceramic and features a soft pink hue, perfect for everyday use or special occasions.',
            dimensions: { diameter: '25cm' },
            inCart: false,
        },

        {
            id: 7,
            img: GoldenSet,
            type: 'cutlery',
            title: 'Golden Set',
            price: '£280',
            count: 30,
            description: 'The Golden Set offers a luxurious dining experience with its gold-plated finish. This cutlery set includes knives, forks, spoons, and more, all designed to elevate your table setting.',
            dimensions: { length: '22cm' },
            inCart: false,
        },
        {
            id: 8,
            img: LampSet,
            type: 'homeware',
            title: 'Lamp Set',
            price: '£250',
            count: 6,
            description: 'The Lamp Set includes two matching table lamps that bring a cohesive look to your decor. Each lamp features a stylish base and a complementary shade, providing both ambient and task lighting.',
            dimensions: { height: '45cm', width: '15cm', depth: '15cm' },
            inCart: false,
        },
        {
            id: 9,
            img: TeaSet,
            type: 'crockery',
            title: 'Tea Set',
            price: '£215',
            count: 8,
            description: 'The Tea Set is perfect for hosting afternoon tea with elegance. This set includes teacups, saucers, a teapot, and a sugar bowl, all featuring a delicate floral pattern.',
            dimensions: { diameter: '20cm' },
            inCart: false,
        },
        {
            id: 10,
            img: VaseSet,
            type: 'ceramics',
            title: 'Ceramic Vase',
            price: '£155',
            count: 11,
            description: 'The Ceramic Vase is a versatile piece that fits well with any decor style. Its simple, classic design allows it to showcase flowers beautifully or stand alone as a decorative item.',
            dimensions: { height: '40cm', diameter: '18cm' },
            inCart: false,
        },
        {
            id: 11,
            img: BlueTableware,
            type: 'tableware',
            title: 'Blue Tableware',
            price: '£270',
            count: 20,
            description: 'The Blue Tableware set brings a pop of color to your dining table. This collection includes plates, bowls, and serving dishes, all featuring a vibrant blue glaze that adds a modern touch.',
            dimensions: { diameter: '27cm' },
            inCart: false,
        },
        {
            id: 12,
            img: WoodenChair,
            type: 'chairs',
            title: 'Wooden Chair',
            price: '£125',
            count: 19,
            description: 'The Wooden Chair combines rustic charm with modern design. Made from high-quality wood, this chair is sturdy and comfortable, making it a perfect addition to any dining or living area.',
            dimensions: { width: '60cm', height: '85cm', depth: '55cm' },
            inCart: false,
        },
        {
            id: 13,
            img: KitchenSet,
            type: 'cutlery',
            title: 'Kitchen Set',
            price: '£140',
            count: 22,
            description: 'The Kitchen Set provides all the essential cutlery you need for everyday meals. Each piece is crafted from durable stainless steel with ergonomic handles for comfortable use.',
            dimensions: { length: '19cm' },
            inCart: false,
        },
        {
            id: 14,
            img: ChristmasSet,
            type: 'tableware',
            title: 'Christmas Set',
            price: '£210',
            count: 49,
            description: 'The Christmas Set is designed to bring festive cheer to your dining table. This tableware collection features holiday-themed designs and includes plates, bowls, and serving platters.',
            dimensions: { diameter: '30cm' },
            inCart: false,
        },
        {
            id: 15,
            img: WhiteTable,
            type: 'tables',
            title: 'White Table',
            price: '£270',
            count: 23,
            description: 'The White Table offers a clean and contemporary look for your dining or work space. Its sturdy construction and sleek white finish make it a versatile piece that complements any decor.',
            dimensions: { width: '120cm', length: '75cm', height: '75cm' },
            inCart: false,
        },
        {
            id: 16,
            img: DinnerPlate,
            type: 'crockery',
            title: 'Dinner Plate',
            price: '£60',
            count: 56,
            description: 'The Dinner Plate is a classic piece of crockery suitable for any meal. Made from high-quality ceramic, it features a simple yet elegant design that complements any table setting.',
            dimensions: { diameter: '28cm' },
            inCart: false,
        },
        {
            id: 17,
            img: MetalChair,
            type: 'chairs',
            title: 'Metal Chair Set',
            price: '£399',
            count: 48,
            description: 'The Metal Chair Set includes a pair of sturdy and stylish chairs. With their sleek metal frames and comfortable seats, these chairs are perfect for both indoor and outdoor use.',
            dimensions: { width: '55cm', height: '80cm', depth: '60cm' },
            inCart: false,
        },
        {
            id: 18,
            img: RusticVase,
            type: 'ceramics',
            title: 'Vase Set',
            price: '£210',
            count: 6,
            description: 'The Vase Set features a collection of three coordinating vases, each with a unique shape and finish. Perfect for displaying flowers or as decorative accents, these vases add a touch of elegance to any room.',
            dimensions: { height: '32cm', diameter: '14cm' },
            inCart: false,
        },
        {
            id: 19,
            img: Serveware,
            type: 'tableware',
            title: 'Serware',
            price: '£180',
            count: 40,
            description: 'Serware is a comprehensive tableware set that includes everything you need for a complete dining experience. This set features plates, bowls, and serving dishes, all with a stylish and modern design.',
            dimensions: { diameter: '26cm' },
            inCart: false,
        },
        {
            id: 20,
            img: WoodenTable,
            type: 'tables',
            title: 'Wooden Table',
            price: '£200',
            count: 15,
            description: 'The Wooden Table is a durable and stylish piece, perfect for any dining room or kitchen. Its natural wood grain and sturdy construction make it a timeless addition to your home.',
            dimensions: { width: '130cm', length: '80cm', height: '75cm' },
            inCart: false,
        },
        {
            id: 21,
            img: DinnerTable,
            type: 'tables',
            title: 'Dinner Table',
            price: '£345',
            count: 10,
            description: 'The Dinner Table is designed to comfortably seat your family and guests. With its spacious top and elegant design, this table is perfect for hosting meals and gatherings.',
            dimensions: { width: '150cm', length: '90cm', height: '75cm' },
            inCart: false,
        },
        {
            id: 22,
            img: ElegantArmchair,
            type: 'chairs',
            title: 'Elegant Armchair',
            price: '£450',
            count: 8,
            description: 'The Elegant Armchair blends classic elegance with modern comfort. Upholstered in luxurious fabric and featuring a sturdy wooden frame, it adds sophistication to any room.',
            dimensions: { width: '120cm', height: '80cm', depth: '60cm' },
            inCart: false,
        },
        {
            id: 23,
            img: ModernCeramicBowl,
            type: 'ceramics',
            title: 'Ceramic Bowl',
            price: '£40',
            count: 15,
            description: 'The Modern Ceramic Bowl is a minimalist addition to your kitchen. Its sleek design and versatile size make it perfect for serving salads or displaying fruit.',
            dimensions: { height: '10cm', diameter: '25cm' },
            inCart: false,
        },
        {
            id: 24,
            img: ModernWallClock,
            type: 'homeware',
            title: 'Wall Clock',
            price: '£50',
            count: 12,
            description: 'The Modern Wall Clock combines functionality with contemporary style. With its minimalist design and silent movement, it adds a sleek accent to any room.',
            dimensions: { diameter: '40cm' },
            inCart: false,
        },
        {
            id: 25,
            img: ClassicDessertSpoonSet,
            type: 'cutlery',
            title: 'Dessert Spoon Set',
            price: '£25',
            count: 25,
            description: 'The Dessert Spoon Set is perfect for serving desserts with elegance. Crafted from durable stainless steel, it combines timeless design with practicality.',
            dimensions: { length: '15cm' },
            inCart: false,
        },
        {
            id: 26,
            img: PorcelainSet,
            type: 'crockery',
            title: 'Porcelain Set',
            price: '£120',
            count: 8,
            description: 'The Porcelain Set combines durability with elegance. Featuring a delicate floral pattern and smooth finish, it enhances your dining experience.',
            dimensions: { diameter: '30cm' },
            inCart: false,
        },
        {
            id: 27,
            img: StonewareServingPlatter,
            type: 'tableware',
            title: 'Serving Platter',
            price: '£75',
            count: 15,
            description: 'The Stoneware Serving Platter is perfect for presenting appetizers or main dishes. Its durable construction and stylish design make it a versatile addition to your tableware collection.',
            dimensions: { diameter: '35cm' },
            inCart: false,
        },
        {
            id: 28,
            img: CoffeeTable,
            type: 'tables',
            title: 'Coffee Table',
            price: '£180',
            count: 10,
            description: 'The Modern Coffee Table features a sleek design with a minimalist aesthetic. Its versatile size and durable build make it an ideal choice for any living room or lounge area.',
            dimensions: { width: '100cm', length: '100cm', height: '45cm' },
            inCart: false,
        },
        {
            id: 29,
            img: OakTable,
            type: 'tables',
            title: 'Oak Table',
            price: '£450',
            count: 3,
            description: 'The Oak Table combines natural beauty with robust construction. Crafted from solid oak, this table is durable and features a rich wood grain that enhances any dining room or kitchen.',
            dimensions: { length: '160cm', width: '100cm', height: '80cm' },
            inCart: false,
        },
        {
            id: 30,
            img: LeatherChair,
            type: 'chairs',
            title: 'Leather Chair',
            price: '£299',
            count: 24,
            description: 'The Leather Chair combines comfort with sophistication. Its luxurious leather upholstery and sturdy wooden frame make it an ideal choice for any modern living room or office.',
            dimensions: { width: '95cm', height: '85cm', depth: '65cm' },
            inCart: false,
        },
        {
            id: 31,
            img: UpholsteredChair,
            type: 'chairs',
            title: 'Upholstered Chair',
            price: '£199',
            count: 10,
            description: 'The Upholstered Chair offers plush comfort and elegant style. Featuring soft fabric upholstery and a supportive backrest, this chair is perfect for lounging or dining.',
            dimensions: { width: '105cm', height: '78cm', depth: '55cm' },
            inCart: false,
        },
        {
            id: 32,
            img: MarbleTable,
            type: 'tables',
            title: 'Marble Table',
            price: '£500',
            count: 5,
            description: 'The Marble Table exudes luxury and sophistication. Featuring a polished marble top and sleek metal legs, this table adds a touch of elegance to your dining or living space.',
            dimensions: { width: '120cm', length: '120cm', height: '75cm' },
            inCart: false,
        },
        {
            id: 33,
            img: BlueCeramicVase,
            type: 'ceramics',
            title: 'Blue Ceramic Vase',
            price: '£180',
            count: 6,
            description: 'The Blue Ceramic Vase adds a contemporary flair to your space. Featuring a bold blue glaze and modern design, it complements any decor while serving as a stunning centerpiece.',
            dimensions: { height: '30cm', diameter: '15cm' },
            inCart: false,
        },
        {
            id: 34,
            img: CrockerySet,
            type: 'crockery',
            title: 'Crockery Set',
            price: '£250',
            count: 6,
            description: 'The Modern Crockery Set combines sleek design with functional elegance. Crafted from fine ceramic, this set includes plates and bowls with a contemporary matte finish, perfect for any dining occasion.',
            dimensions: { diameter: '22cm' },
            inCart: false,
        },
        {
            id: 35,
            img: RusticPlateSet,
            type: 'crockery',
            title: 'Rustic Plate Set',
            price: '£150',
            count: 7,
            description: 'The Rustic Plate Set brings rustic charm to your table. Handcrafted from stoneware, each plate features a unique glaze finish and is ideal for everyday meals with a touch of elegance.',
            dimensions: { diameter: '28cm' },
            inCart: false,
        },
        {
            id: 36,
            img: FloralTableware,
            type: 'tableware',
            title: 'Floral Tableware',
            price: '£110',
            count: 15,
            description: 'The Floral Tableware set features delicate floral patterns for a touch of nature at your dining table. This collection includes plates, bowls, and serving dishes, perfect for everyday use.',
            dimensions: { diameter: '27cm' },
            inCart: false,
        },
        {
            id: 37,
            img: VintageTableware,
            type: 'tableware',
            title: 'Vintage Tableware',
            price: '£180',
            count: 6,
            description: 'The Vintage Tableware set brings timeless elegance to your dining setting. Crafted from ceramic, each piece features intricate designs and a vintage-inspired finish for a nostalgic charm.',
            dimensions: { diameter: '26cm' },
            inCart: false,
        },
        {
            id: 38,
            img: WoodenCutlery,
            type: 'cutlery',
            title: 'Wooden Cutlery Set',
            price: '£120',
            count: 15,
            description: 'The Wooden Cutlery Set adds a rustic charm to your dining table. Crafted from sustainable wood, this set includes knives, forks, and spoons that are both eco-friendly and stylish.',
            dimensions: { length: '19cm' },
            inCart: false,
        },
        {
            id: 39,
            img: GoldPlatedCutlery,
            type: 'cutlery',
            title: 'Gold-Plated Cutlery',
            price: '£150',
            count: 8,
            description: 'The Gold-Plated Cutlery adds a touch of luxury to your table setting. Crafted from high-quality stainless steel with a polished gold finish, this set includes forks, knives, and spoons, perfect for formal dining.',
            dimensions: { length: '22cm' },
            inCart: false,
        },
    ]
}